const locations = [
  "29. Novembra",
  "Ada Ciganlija",
  "Altina",
  "Andrićev venac",
  "Voždovac (sve podlokacije)",
  "Autokomanda",
  "Avala",
  "Banjica",
  "Beli potok",
  "Braće Jerković",
  "Bubanj potok",
  "Dušanovac",
  "Farmaceutski fakultet",
  "Jajinci",
  "Konjarnik",
  "Lekino brdo",
  "Marinkova bara",
  "Pašino brdo",
  "Stepa Stepanović",
  "Šumice",
  "Torlak",
  "Trošarina",
  "Veljko Vlahović",
  "Voždovac",
  "Autoput",
  "Bajlonijeva pijaca",
  "Banija",
  "Banovo brdo",
  "Barajevo",
  "Batajnica",
  "Belaci",
  "Bele vode",
  "Beograd na vodi",
  "Centar (sve podlokacije)",
  "Beograđanka ( centar )",
  "Centar (uži)",
  "Knez Mihajlova ( centar )",
  "Kneza Miloša ( centar )",
  "Politika ( centar )",
  "Stari Grad",
  "Studentski Trg ( centar )",
  "Terazije ( centar )",
  "Trg Republike ( centar )",
  "Bežanija",
  "Bežanijska kosa (sve podlokacije)",
  "Bežanijska kosa I",
  "Bežanijska kosa II",
  "Bežanijska kosa III",
  "Palilula (sve podlokacije)",
  "Bogoslovija",
  "Botanička bašta",
  "Cvijićeva",
  "Hadžipopovac",
  "Hala Pionir",
  "Karaburma",
  "Kotež",
  "Krnjača",
  "Ovča",
  "Padinska skela",
  "Palilula",
  "Palilulska pijaca",
  "Poštanska štedionica",
  "Profesorska kolonija",
  "Rospi ćuprija",
  "Tašmajdan",
  "Viline vode",
  "Višnjica",
  "Višnjička banja",
  "Borča (Sve podlokacije)",
  "Borča I",
  "Borča II",
  "Borča III",
  "Borča IV",
  "Borča V",
  "Brodogradilište Beograd",
  "Brzi Brod",
  "Zvezdara (sve podlokacije)",
  "Bulbuder",
  "Bulevar Kr. Aleksandra",
  "Cvetanova ćuprija",
  "Cvetkova pijaca",
  "Denkova bašta",
  "Đeram pijaca",
  "Gradska bolnica",
  "Kluz",
  "Lion",
  "Lipov lad",
  "Mali mokri lug",
  "Novo groblje",
  "Olimp",
  "Rudo",
  "Severni bulevar",
  "Slavujev venac",
  "Smederevski put",
  "Učiteljsko naselje",
  "Veliki mokri lug",
  "Vukov spomenik",
  "Zeleno Brdo",
  "Zira",
  "Zvezdara",
  "Zvezdarska Šuma",
  "Cerak vinogradi",
  "Cerak",
  "Cerski venac",
  "Vračar (sve podlokacije)",
  "Crveni krst",
  "Čubura",
  "Cvetni trg",
  "Gradic Pejton",
  "Južni bulevar",
  "Kalenić pijaca",
  "Neimar",
  "Slavija",
  "Vračar (Centar)",
  "Vračar (Hram)",
  "Čukarica",
  "Čukarička padina",
  "Dedinje (sve podlokacije)",
  "Dedinje (25. maj)",
  "Dedinje (Beli dvor)",
  "Dedinje (RTV Pink)",
  "Dobanovci",
  "Dorćol (sve podlokacije)",
  "Donji Dorćol",
  "Dunavski kej",
  "Gornji Dorćol",
  "Strahinjića Bana",
  "Filmski grad",
  "Galenika",
  "Glumčevo brdo",
  "Golf naselje",
  "Greda",
  "Grocka",
  "Gundulićev venac",
  "Hipodrom",
  "Ibarska magistrala",
  "Industrijska zona jug",
  "Institut za majku i dete",
  "Jabučki rit",
  "Jelovac",
  "Julino brdo",
  "Kablar",
  "Kalemegdan",
  "Kaluđerica",
  "Kanarevo brdo",
  "Karađorđeva",
  "Kijevo",
  "Klinički centar",
  "Kneževac",
  "Kopitareva gradina",
  "Kosančićev venac",
  "Košutnjak",
  "Kumodraž (sve podlokacije)",
  "Kumodraž I",
  "Kumodraž II",
  "Labudovo brdo",
  "Ledine",
  "Leštane",
  "Lipovačka šuma",
  "Lisičji jarak",
  "Lisičji potok",
  "Mačkov kamen",
  "Makiš",
  "Manjež",
  "Medaković (sve podlokacije)",
  "Medak padina",
  "Medaković I",
  "Medaković II",
  "Medaković III",
  "Miljakovac (sve podlokacije)",
  "Miljakovac I",
  "Miljakovac II",
  "Miljakovac III",
  "Milka Protic (KP dom)",
  "Mirijevo (sve podlokacije)",
  "Mirijevo I",
  "Mirijevo II",
  "Mirijevo III",
  "Mirijevo IV",
  "Novi Beograd (sve podlokacije)",
  "Novi Beograd",
  "Novi Beograd Blok 1 (Fontana)",
  "Novi Beograd Blok 10",
  "Novi Beograd Blok 11 (Hotel Jugoslavija)",
  "Novi Beograd Blok 11a (Opština NBG)",
  "Novi Beograd Blok 11b",
  "Novi Beograd Blok 11c (Stari Merkator)",
  "Novi Beograd Blok 12 (YUBC)",
  "Novi Beograd Blok 13 (Palata federacije)",
  "Novi Beograd Blok 14 (Park Ušće)",
  "Novi Beograd Blok 15 (Park Ušće)",
  "Novi Beograd Blok 16 (Ušće šoping centar)",
  "Novi Beograd Blok 17 (Staro sajmište)",
  "Novi Beograd Blok 19 (Sava Centar)",
  "Novi Beograd Blok 19a",
  "Novi Beograd Blok 2",
  "Novi Beograd Blok 20 (Hotel Hayat)",
  "Novi Beograd Blok 21 (10. Gimnazija)",
  "Novi Beograd Blok 22",
  "Novi Beograd Blok 23",
  "Novi Beograd Blok 24 (Super Vero)",
  "Novi Beograd Blok 25 (Arena)",
  "Novi Beograd Blok 26",
  "Novi Beograd Blok 28 (Potkovica)",
  "Novi Beograd Blok 29",
  "Novi Beograd Blok 3",
  "Novi Beograd Blok 30 (B92)",
  "Novi Beograd Blok 31 (Merkator)",
  "Novi Beograd Blok 32 (Crkva sv. Dimitrija)",
  "Novi Beograd Blok 33 (Genex kula)",
  "Novi Beograd Blok 34 (Studentski grad)",
  "Novi Beograd Blok 35 (SC 11. April)",
  "Novi Beograd Blok 37",
  "Novi Beograd Blok 38 (OŠ Ratko Mitrović)",
  "Novi Beograd Blok 39",
  "Novi Beograd Blok 4 (Politehnička akademija)",
  "Novi Beograd Blok 40",
  "Novi Beograd Blok 41 (Expo centar)",
  "Novi Beograd Blok 41a (GTC)",
  "Novi Beograd Blok 42",
  "Novi Beograd Blok 43 (Buvlja pijaca)",
  "Novi Beograd Blok 44 (Piramida)",
  "Novi Beograd Blok 45 (TC Enjub)",
  "Novi Beograd Blok 49",
  "Novi Beograd Blok 5",
  "Novi Beograd Blok 53 (Kvantaš)",
  "Novi Beograd Blok 58",
  "Novi Beograd Blok 60",
  "Novi Beograd Blok 60 (Airport City)",
  "Novi Beograd Blok 61",
  "Novi Beograd Blok 62",
  "Novi Beograd Blok 63",
  "Novi Beograd Blok 64",
  "Novi Beograd Blok 65",
  "Novi Beograd Blok 66 (Tramvajska štala)",
  "Novi Beograd Blok 66a",
  "Novi Beograd Blok 67 (Belvil)",
  "Novi Beograd Blok 67a",
  "Novi Beograd Blok 68",
  "Novi Beograd Blok 7 (Paviljoni)",
  "Novi Beograd Blok 70 (Kineski TC)",
  "Novi Beograd Blok 70a",
  "Novi Beograd Blok 71",
  "Novi Beograd Blok 72",
  "Novi Beograd Blok 7a (Paviljoni)",
  "Novi Beograd Blok 8 (Paviljoni)",
  "Novi Beograd Blok 8a",
  "Novi Beograd Blok 8a (Paviljoni)",
  "Novi Beograd Blok 9",
  "Novi Beograd Blok 9a (Dom Zdravlja)",
  "Obilićev venac",
  "Orlovača",
  "Ostružnica",
  "Palata pravde",
  "Pančevački most",
  "Partizanov stadion",
  "Petlovo brdo",
  "Pionirski park",
  "Plavi Horizonti",
  "Pregrevica",
  "Radiofar",
  "Rakovica",
  "Resnik",
  "Retenzija",
  "Reva",
  "Rušanj",
  "Sarajevska",
  "Sava mala",
  "Savski trg",
  "Savski venac",
  "Senjak",
  "Skadarlija",
  "Skojevsko naselje",
  "Sopot",
  "Sremčica",
  "Sunčana padina",
  "Sunčani breg",
  "Surčin",
  "Tehnicki fakulteti",
  "Topčider",
  "Topličin venac",
  "Tošin bunar",
  "Trešnja",
  "Vidikovac",
  "Vidikovačka padina",
  "Vidikovački venac",
  "Vinča",
  "Vojvode Vlahovića",
  "Žarkovo",
  "Zeleni venac",
  "Železnik",
  "Zemun (sve podlokacije)",
  "Zemun (13. maj)",
  "Zemun (Bačka)",
  "Zemun (Cara Dušana)",
  "Zemun (Centar)",
  "Zemun (Ćukovac)",
  "Zemun (Donji grad)",
  "Zemun (Gardoš)",
  "Zemun (Gornji grad)",
  "Zemun (Kalvarija)",
  "Zemun (Kej)",
  "Zemun (Marije Bursać)",
  "Zemun (Meandri)",
  "Zemun (Nova Galenika)",
  "Zemun (Novi Grad)",
  "Zemun (Save Kovačevića)",
  "Zemun (Sutjeska)",
  "Zemun (Teleoptik)",
  "Zemun Polje",
  "Zvezdin stadion",
];
